channels:
  # Define conda channels here.
  - defaults
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.8.17
  - pip=23.1.2
  - pip:
    # Define pip packages here.
    # https://pypi.org/
      - playwright=1.36.0
      - pytest=7.4.0
      - pytest-playwright=0.3.3
      - pandas=1.5.3
      - openpyxl=3.1.2
      - pre-commit=3.3.3

